# Generated by Django 6.0.5 on 2026-06-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('session', 'Session'), ('exam', 'Exam'), ('holiday', 'Holiday'), ('hostel', 'Hostel'), ('unavail', 'Unavailable')], max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('related_module', models.CharField(blank=True, max_length=50)),
                ('related_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
